# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "Î»"
[character]      # The name of the module we are configuring is "character"
symbol = "Î»"     # The "symbol" segment is being set to "Î»"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
disabled = true # Don't show command duration

[line_break]
disabled = false

[hostname]
ssh_only = true

[username]
style_user = "bold dimmed blue"
show_always = true

[directory]
truncate_to_repo = true # truncates directory to root folder if in github repo
prefix = "ğŸ“‚ï¸  "
style = "bold italic #87A752"
